### ISSUE TITLE
Properties of a Correct Solution 

### ISSUE THREAD

**Issue by andreamclemeno** [parsamorsal/Inverted-Pendulum#16]
Hi @parsamorsal !

Almost done!! This is regarding your Properties of a Correct Solution section on page 8. I think this also has to do with your input and output. From here, I guess that your output is a function that has a lot of successes meaning that it learned how "to maintain the pole in the stabilized position for an unlimited time".

I am not sure if I am right. But if I am not, how do we determine if the solution has learned?

Andrea

**Comment by smiths** [comment]
@parsamorsal, you should definitely brainstorm, but it might be difficult to come up with properties in your case.  The implied output of your program is the table of values that come from machine learning.  I don't know if there is anything that we can say in general about this table.  I'm not an expert by any means, but the table doesn't really have a physical meaning.

There will be tests that you can do to verify your work, but that will be documented in the Verification and Validation plan.

**Comment by parsamorsal** [comment]
That sentence was a little vague because at that time I didn't have a good estimation of how good the IPP solver would work. 
After developing the code a little more and running some tests, I arrived at a more clear definition of the solution with regard to input and outputs. 
I have edited that sentence so it would also be consistent with my VnV plan dd96397
